version: '3'
services:
  php:
    image: php:7-fpm
    container_name: php
    restart: unless-stopped
    volumes:
      - ../app:/var/www
      - ./env-vars.conf:/usr/local/etc/php-fpm.d/env-vars.conf
    tty: true
    networks:
      - php

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ../app:/var/www
      - ../nginx/php.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - php

networks:
  php:
