version: '3'
services:
  php:
    image: doppler-php-dotenv
    container_name: php
    restart: unless-stopped
    environment:
      - DOPPLER_TOKEN
    tty: true
    networks:
      - php

  nginx:
    image: nginx
    container_name: nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ../app:/var/www
      - ../nginx/php.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - php

networks:
  php:
